spring.application.name=cargora
server.port=8080
# MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/cargora
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#JWT
jwt.secret=7526a4fd1ef27ae40c5080b667db1031b907342a19d793a8d74de1b18eb392d7
jwt.expiration=3600000